### ISSUE TITLE
problem with deleting profiles...

### ISSUE THREAD

**Issue by logallsite** [sarahavilov/autofillforms-e10s#1]
not work add complete fron as profile
dones not save as they were placed characters
nor work correct

**Comment by zeroprss** [comment]
not follow the order of writing

**Comment by sarahavilov** [comment]
@logallsite this issue is fixed on the latest dev version
https://github.com/sarahavilov/autofillforms-e10s/blob/master/builds/packed/chrome.zip?raw=true

Download the ZIP file, extract it in a folder. Now open chrome://extensions/ and activate developer option. Point your browser to the root directory.

**Comment by sarahavilov** [comment]
@zeroprss I am not following

**Comment by zeroprss** [comment]
what code needs to go , one row below.? ex :
1
2
3.
when you give autofill remain . as I wrote.

**Comment by zeroprss** [comment]
same problem in version 0.1.1 not working
It does not work ( <br> ) how it works in firefox to pass a line below
Helppppppppp

**Comment by zeroprss** [comment]
( <,br,> ) without commas firefox works

**Comment by zeroprss** [comment]
same problem in version 0.1.1 not working
It does not work ( ( <,br,> )
) how it works in firefox to pass a line below
Helppppppppp

**Comment by sarahavilov** [comment]
As of version 0.1.2 it is possible to have multi-line values. You can use "\n" or "<br>" to break the current line.

Thanks for the report.
