### ISSUE TITLE
high cpu usage with many tabs?

### ISSUE THREAD

**Issue by danielmotaleite** [sarahavilov/autofillforms-e10s#20]
i use firefox with many tab (about 100) and i notice that the browser was slow (duh!), so i installed task manager add-on (https://addons.mozilla.org/en-US/firefox/addon/task-manager/) and changed the refresh to 5s. I notice then that autofil was every 2 refresh ( ~10s) showing using 100% cpu (or higher!!?)

almost all tabs are in "restore state" (restore the page after a crash, not really loaded) and had some static pages and about 3 kibana pages, 2 with autorefresh every 5 minutes. autofill should be using any cpu at all, as i was not loading pages nor using it.

So something is making autofil wake up and use a lot of cpu (maybe related with the many open tabs), or task manager have some bug with it (as it is weird a higher than 100% cpu usage! ) :)

**Comment by sarahavilov** [comment]
We are moving to the WebExtension version. I am pretty sure this issue is fixed on the new version. To try please follow:

1. Open about:debugging in a browser tab
2. Download the dev version here, https://github.com/sarahavilov/autofillforms-e10s/archive/master.zip
3. Extract it to a local directory and point the "Load Temporary add-on" to the manifest.json.


Please reopen it you are still experiencing this issue.
