### ISSUE TITLE
New fields not visible in context menu

### ISSUE THREAD

**Issue by icaine** [sarahavilov/autofillforms-e10s#4]
I created a field (randexp => "/\w{5,8}/";)  but i cant find it in RMB context menu.

**Comment by sarahavilov** [comment]
This should have been fixed in my last commit. Please update to the latest dev version; https://github.com/sarahavilov/autofillforms-e10s/blob/master/builds/packed/firefox.xpi?raw=true

In the latest dev, context menu should get update singnal once a new rule is added or being removed. Note that your rule must exists in both "rules" and "profile" section

**Comment by icaine** [comment]
I see, i didnt set it in Rules section.

Imho it should not be mandatory to have records in both sections and if so, it should be done via single action (both in a single form?)

**Comment by sarahavilov** [comment]
Agreed. Profile section is now responsible for context menu creation.

**Comment by icaine** [comment]
Works, thank you:)
